kind = "web"
previewPath = "/"
title = "Microblog"
version = "1.0.0"
id = "artifacts/microblog"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20925

[services.development]
run = "pnpm --filter @workspace/microblog run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/microblog", "run", "build" ]
publicDir = "artifacts/microblog/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20925"
BASE_PATH = "/"
