// Fallback SQL dumper used only when `mysqldump` is not installed in the
// environment. Prefer `mysqldump` for production backups when available
// (see DECISIONS.md, 2026-05-03 entry).
import mysql from 'mysql2/promise';
import fs from 'fs';
import path from 'path';

const conn = await mysql.createConnection({
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT || 3306),
  user: process.env.DB_USER,
  password: process.env.DB_PASS,
  database: process.env.DB_NAME,
  ssl: process.env.DB_SSL === 'true' ? {} : undefined,
  multipleStatements: true,
  connectTimeout: 30000,
});

const dbName = process.env.DB_NAME;
const outDir = process.argv[2] || '/home/runner/db_backups';
fs.mkdirSync(outDir, { recursive: true });
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const outPath = path.join(outDir, `${dbName}-${stamp}.sql`);
const out = fs.createWriteStream(outPath);

function esc(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (v instanceof Date) return `'${v.toISOString().slice(0, 23).replace('T', ' ')}'`;
  if (Buffer.isBuffer(v)) return `0x${v.toString('hex')}`;
  const s = String(v);
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\u0000/g, '\\0')}'`;
}

out.write(`-- Backup of \`${dbName}\` taken at ${new Date().toISOString()}\n`);
out.write(`-- Generated by scripts/db-backup.mjs\n`);
out.write(`SET FOREIGN_KEY_CHECKS=0;\n`);
out.write(`SET UNIQUE_CHECKS=0;\n\n`);

const [tables] = await conn.query(
  `SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME`,
  [dbName]
);

let totalRows = 0;
for (const { TABLE_NAME: t } of tables) {
  const [[ddl]] = await conn.query(`SHOW CREATE TABLE \`${t}\``);
  out.write(`-- -----------------------------------\n-- Table: ${t}\n-- -----------------------------------\n`);
  out.write(`DROP TABLE IF EXISTS \`${t}\`;\n`);
  out.write(`${ddl['Create Table']};\n\n`);

  const [rows] = await conn.query(`SELECT * FROM \`${t}\``);
  if (rows.length === 0) { out.write(`-- (no rows)\n\n`); continue; }
  const cols = Object.keys(rows[0]);
  const colList = cols.map(c => `\`${c}\``).join(',');
  for (let i = 0; i < rows.length; i += 200) {
    const batch = rows.slice(i, i + 200);
    const vals = batch.map(r => `(${cols.map(c => esc(r[c])).join(',')})`).join(',\n  ');
    out.write(`INSERT INTO \`${t}\` (${colList}) VALUES\n  ${vals};\n`);
  }
  out.write(`\n`);
  totalRows += rows.length;
  console.log(`  dumped ${t}: ${rows.length} rows`);
}

out.write(`SET FOREIGN_KEY_CHECKS=1;\nSET UNIQUE_CHECKS=1;\n`);
await new Promise(res => out.end(res));
await conn.end();

const size = fs.statSync(outPath).size;
console.log(`\nBackup complete: ${outPath}`);
console.log(`Size: ${(size / 1024).toFixed(1)} KB | Tables: ${tables.length} | Total rows: ${totalRows}`);
